language: java
jdk: openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_09bb2ac36cc3_key -iv $encrypted_09bb2ac36cc3_iv -in id_rsa.enc -out ~\/id_rsa -d
- mkdir ~\/.ssh & mv -f ~/id_ras ~\/.ssh & chmod 600 ~\/.ssh/id_rsa

addons:
  ssh_known_hosts: 139.9.247.199

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
