language: java
jdk: openjdk8
script: "mvn cobertura:cobertura"

before_install:
- mkdir ~/.ssh & chmod 755 ~/.ssh & cd ~ & touch ./.ssh/id_rsa & chmod 777 ./.ssh/id_rsa
- openssl aes-256-cbc -K $encrypted_09bb2ac36cc3_key -iv $encrypted_09bb2ac36cc3_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d

addons:
  ssh_known_hosts: 139.9.247.199

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
